name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start OWASP ZAP
      run: |
        zap.bat -daemon -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
      continue-on-error: true

    - name: Wait for ZAP to start
      run: Start-Sleep -Seconds 30

    - name: Run ZAP Baseline Scan
      run: |
        zap-baseline.bat -t http://localhost/laradesk-1.1.2 -r zap_report.html -J zap_report.json -z "3aq6vrr0ld2i7dcom51mgtfhap"

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap_report.html

    - name: Upload ZAP JSON Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-json
        path: zap_report.json
