name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start OWASP ZAP
      run: |
        & "C:\Program Files\ZAP\Zed Attack Proxy\zap.bat" -daemon -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
      shell: powershell

    - name: Wait for ZAP to start
      run: Start-Sleep -Seconds 30
      shell: powershell

    - name: Run ZAP Scan
      run: |
        powershell -File .\github\scripts\zap_scan.ps1
      shell: powershell

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap_report.html

    - name: Upload ZAP JSON Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-json
        path: zap_report.json
