name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify OWASP ZAP Installation
      run: |
        dir "C:\Program Files\ZAP\Zed Attack Proxy"
        if (-not (Test-Path "C:\Program Files\ZAP\Zed Attack Proxy\zap.bat")) {
          Write-Error "OWASP ZAP is not installed in the expected location."
        }
      shell: powershell

    - name: Print Environment Variables
      run: |
        Get-ChildItem Env:
      shell: powershell

    - name: Start OWASP ZAP
      run: |
        & "C:\Program Files\ZAP\Zed Attack Proxy\zap.bat" -daemon -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true > zap_log.txt 2>&1
        Get-Content zap_log.txt
      shell: powershell

    - name: Wait for ZAP to start
      run: Start-Sleep -Seconds 30
      shell: powershell

    - name: Run ZAP Scan
      run: |
        powershell -File .\github\scripts\zap_scan.ps1
      shell: powershell

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap_report.html

    - name: Upload ZAP JSON Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-json
        path: zap_report.json
